### ISSUE TITLE
Verbose issue

### ISSUE THREAD

**Issue by cchehoud** [PennChopMicrobiomeProgram/unassigner#4]
When running with verbose flag:

python unassign.py --query_fp seq.fasta --output_dir unassigner_results/ --noref --num_cpus 4 --verbose

Error message:

Traceback (most recent call last):
  File "unassign.py", line 3, in <module>
    main()
  File "/media/THING2/christel/12_HIV/typestrains/unassigner/unassign/command.py", line 32, in main
    logging.basicConfig(level=logging.INFO)
NameError: global name 'logging' is not defined

**Comment by cchehoud** [comment]
Thank you for the blast from the past!
